### ISSUE TITLE
Missing evaluation functions and typos in README

### ISSUE THREAD

**Issue by coldmanck** [yuweihao/KERN#1]
This two functions are missing `calculate_mR_from_evaluator_list`, `eval_entry` when I executed `eval_rels.py` and faced `ImportError` in [this line](https://github.com/yuweihao/KERN/blob/8e5937bcd911b3aa5e87bbedcc4f0c29555c2dd2/models/eval_rels.py#L8). Could please check it for me?

Btw, for the step 5 in SETUP section in README.MD, `./scripts/refine_for_detection.sh` is not there in your directory and it seems exists only in the original neural-motifs repo. I guess you have changed it to `train_kern_sgdet.py`?

**Comment by yuweihao** [comment]
Dear Dr. Chiou,

Really thanks for your reminder. I forgot to replace ```eval_rels.py``` with the new one when I collated the code to GitHub . Sorry for my carelessness to puzzle you. I have updated it just now.

As for second question, yes, it should be ```train_kern_sgdet.py```. I have corrected this typo. Thank you for your reminder again.

Weihao

**Comment by coldmanck** [comment]
Thank you @yuweihao!

**Comment by yuweihao** [comment]
(^_^) Thank you too. @coldmanck

**Comment by ystluffy** [comment]
> Dear Dr. Chiou,
> 
> Really thanks for your reminder. I forgot to replace `eval_rels.py` with the new one when I collated the code to GitHub . Sorry for my carelessness to puzzle you. I have updated it just now.
> 
> As for second question, yes, it should be `train_kern_sgdet.py`. I have corrected this typo. Thank you for your reminder again.
> 
> Weihao



> Dear Dr. Chiou,
> 
> Really thanks for your reminder. I forgot to replace `eval_rels.py` with the new one when I collated the code to GitHub . Sorry for my carelessness to puzzle you. I have updated it just now.
> 
> As for second question, yes, it should be `train_kern_sgdet.py`. I have corrected this typo. Thank you for your reminder again.
> 
> Weihao

Hi @yuweihao  Thanks for sharing the code! 
Have you updated `eval_rels.py` ? I just download your code but the two functions are still missing.

**Comment by yuweihao** [comment]
> > Dear Dr. Chiou,
> > Really thanks for your reminder. I forgot to replace `eval_rels.py` with the new one when I collated the code to GitHub . Sorry for my carelessness to puzzle you. I have updated it just now.
> > As for second question, yes, it should be `train_kern_sgdet.py`. I have corrected this typo. Thank you for your reminder again.
> > Weihao
> 
> > Dear Dr. Chiou,
> > Really thanks for your reminder. I forgot to replace `eval_rels.py` with the new one when I collated the code to GitHub . Sorry for my carelessness to puzzle you. I have updated it just now.
> > As for second question, yes, it should be `train_kern_sgdet.py`. I have corrected this typo. Thank you for your reminder again.
> > Weihao
> 
> Hi @yuweihao Thanks for sharing the code!
> Have you updated `eval_rels.py` ? I just download your code but the two functions are still missing.

Hi @ystluffy , thanks for noticing our work.
I have checked it again and I find I have updated it. Please just download the code from this repo but not other repos which may be old. You could also post your detailed error information and maybe I could find the cause.

**Comment by ystluffy** [comment]
> > > Dear Dr. Chiou,
> > > Really thanks for your reminder. I forgot to replace `eval_rels.py` with the new one when I collated the code to GitHub . Sorry for my carelessness to puzzle you. I have updated it just now.
> > > As for second question, yes, it should be `train_kern_sgdet.py`. I have corrected this typo. Thank you for your reminder again.
> > > Weihao
> > 
> > 
> > > Dear Dr. Chiou,
> > > Really thanks for your reminder. I forgot to replace `eval_rels.py` with the new one when I collated the code to GitHub . Sorry for my carelessness to puzzle you. I have updated it just now.
> > > As for second question, yes, it should be `train_kern_sgdet.py`. I have corrected this typo. Thank you for your reminder again.
> > > Weihao
> > 
> > 
> > Hi @yuweihao Thanks for sharing the code!
> > Have you updated `eval_rels.py` ? I just download your code but the two functions are still missing.
> 
> Hi @ystluffy , thanks for noticing our work.
> I have checked it again and I find I have updated it. Please just download the code from this repo but not other repos which may be old. You could also post your detailed error information and maybe I could find the cause.

I have no idea what happened but I download the code again and now it works. Thank you
